name: stoPET-model-v1.0
channels:
  - defaults

dependencies:
  - python3.7+
  - python2.7+
  - pip
  # Core scientific python
  - numpy
  - netcdf4
  - scipy
  # python embedded libraries
  - datetime
  - os
  - sys
  
